# Generated by Django 5.1.3 on 2025-08-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='car',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='brand',
            field=models.CharField(default='brand', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_name',
            field=models.CharField(default='car_name', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(default='full_name', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
