# Generated by Django 5.1.3 on 2025-08-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_reservation_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='city',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default='2023-01-02'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.CharField(default='price', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
